version: '3'
services:
  v2ray:
    image: v2ray/official
    container_name: v2ray
    volumes:
    - ./v2ray/config.json:/etc/v2ray/config.json
    - ./log/v2ray:/var/log/v2ray
    expose:
    - "10086"
    restart: unless-stopped
  nginx:
    image: nginx:stable-alpine
    container_name: v2ray_nginx
    volumes:
      - ./ssl:/etc/v2ray 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d 
      - ./html:/usr/share/nginx/html
      - ./log/nginx:/var/log/nginx
    ports:
    - "443:443"
    links:
    - v2ray:v2ray
    restart: unless-stopped
networks:
  default:
    external:
      name: v2ray