version: "3.7"
services:
  v2ray:
    image: v2ray/official
    container_name: v2ray
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json
      - ./v2ray/log:/var/log/v2ray
    expose:
      - "10086"
    restart: unless-stopped
  nginx:
    image: nginx:stable-alpine
    container_name: v2ray_nginx
    volumes:
      - ./ssl:/etc/v2ray
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./html:/usr/share/nginx/html
    ports:
      - "443:443"
    links:
      - v2ray:v2ray
    restart: unless-stopped
